Fix typo assesment -> assessment
apple/swift-docc pull request #445
Opened 2022-12-31 22:13 UTC by stzn

Bug/issue #, if applicable: 

## Summary

I found typos in some places, so fixed them. please correct me if I am wrong.

## Dependencies

None

## Testing

Please check the spelling

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [ ] ~Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- [ ] ~Updated documentation if necessary~

2023-01-03 18:31 UTC, ethan-kusters commented
@swift-ci please test

2023-01-09 17:50 UTC, Kyle-Ye commented on Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
>                      }
Is this a breaking change for swift-docc-render? @ethan-kusters

2023-07-06 18:01 UTC, Kyle-Ye commented
@swift-ci please test

2023-07-07 02:55 UTC, Kyle-Ye requested changes
Would you mind writing a test case for it before merging?

2023-07-07 02:58 UTC, Kyle-Ye commented on Sources/SwiftDocC/SwiftDocC.docc/Resources/RenderNode.spec.json
>                      }
The is confirmed on swift-docc-render and swift-docc

2023-07-07 12:19 UTC, stzn commented
I see. Thank you. What kind of tests do I need to add? Sorry, it,s my first time contribution and not sure what to do actually.

2023-07-07 13:07 UTC, Kyle-Ye commented
It corresponds to the code in `RenderHierarchyLandmark.swift`.

After searching in project, it turns out that we currently do not have any sort of test case for openapi json file. Maybe we can add such later when swift-openapi-generator is mature.

2023-07-07 13:07 UTC, Kyle-Ye approved these changes

2023-07-07 13:07 UTC, Kyle-Ye commented
@swift-ci please test

2023-07-07 13:17 UTC, merged