Disable the DefaultDiagnosticConsoleFormatter because of index-out-of-bounds crash
apple/swift-docc pull request #723
Opened 2023-10-03 22:38 UTC by d-ronnqvist

Bug/issue #, if applicable: https://github.com/apple/swift-docc/issues/678

## Summary

Always use `IDEDiagnosticConsoleFormatter` to format diagnostics to avoid a crash.

This is a smaller change than it would be to revert the PR that introduced `DefaultDiagnosticConsoleFormatter`.

## Dependencies

None.

## Testing

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- ~[ ] Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- ~[ ] Updated documentation if necessary~

2023-10-03 22:41 UTC, d-ronnqvist commented
@swift-ci please test

2023-10-03 22:42 UTC, d-ronnqvist commented
We'll hold this PR until the next Documentation Workgroup meeting where we'll discuss https://github.com/apple/swift-docc/issues/678

2023-10-25 06:30 UTC, Kyle-Ye commented
https://github.com/apple/swift-docc/issues/678#issuecomment-1778595554

Considering #678 seems to be fixed. Can we speed up the process of the cherry-pick to release/5.10 and observe the feedback of 5.10 toolchain instead of merging this to release/5.10. @d-ronnqvist 

I'd like to know what's your thoughts on this? cc @arthurcro

2023-10-25 15:29 UTC, d-ronnqvist commented
> Considering [#678 (comment)](https://github.com/apple/swift-docc/issues/678#issuecomment-1778595554) seems to be fixed. Can we speed up the process of the cherry-pick to release/5.10 and observe the feedback of 5.10 toolchain instead of merging this to release/5.10. @d-ronnqvist
> 
> I'd like to know what's your thoughts on this? cc @arthurcro

I'm out all of this week and likely part of next week as well so I'll leave that decision to @QuietMisdreavus and @franklinsch. In the mean time I'll mark this PR as a draft to keep it around and also indicate that we may not need it.

2023-10-25 21:03 UTC, patshaughnessy requested changes

2023-10-25 21:03 UTC, patshaughnessy commented on Sources/SwiftDocC/Infrastructure/Diagnostics/DiagnosticConsoleWriter.swift
> +        formattingOptions = [.formatConsoleOutputForTools]
Should we also pass `formattingOptions` into the call to `makeDiagnosticFormatter` just below? Right now it looks like we pass the original `options` value into `makeDiagnosticFormatter` which appears incorrect.

However, based on the conversation here we might end up just closing this PR out anyway...

2023-11-08 11:14 UTC, d-ronnqvist commented
Closing this since https://github.com/apple/swift-docc/issues/678 is closed.

2023-11-08 11:14 UTC, closed without merging

2023-11-08 11:30 UTC, Kyle-Ye commented
Some note here:
Some cherry-pick fix for #678 is still open. I've tried to ping and send private message to the related owner but still got no response. It will still cause crash on latest swift/5.10 toolchain.