Fix Availability Selection in Symbol Graph Loader
apple/swift-docc pull request #803
Opened 2024-01-18 15:38 UTC by sofiaromorales

Bug/issue #, if applicable:  rdar://118207413

## Summary

Currently, when the availability information comes from the SGFs and the Info.plist default availability section, the symbol graph loader fills each symbol with all the defined platforms in the Info.plist. This results in incorrect availability information being displayed in the subsequent documentation, as symbols are shown as available for platforms where they are not actually available, and, since DocC selects only one symbol from the unified symbol graph, the chosen symbol does not have the correct availability information for all its variants.

With this fix, for every symbol loaded from SGFs of the same module, we only add a single platform where that symbol is defined. If there's default availability information defined in the Info.plist, we use it to fill any missing introduced version information, but only if the symbol exists in that platform.

-----

Before this fix, the symbol graph loading looked like this (from the availability perspective):

#### **Input:** 
tvOS-swift.symbols.json:
**A** -> { domain: tvOS }
watchOS-swift.symbols.json:
**A** -> { domain: watchOS, introduced: 8 }

Info.plist:
| tvOS | 3.0 |
| watchOS | 2.0 |
| iOS | 1.0 |

#### **Symbols after symbol graph loading:**
**A** -> { { domain: tvOS, introduced: 3 }, { domain: watchOS, introduced: 2.0 }, { domain: iOS, introduced: 1.0 } }
 **A** -> { { domain: tvOS, introduced: 3 }, { domain: watchOS, introduced: 8.0 }, { domain: iOS, introduced: 1.0 } }

#### **Resulting symbol availability in the docs:**
**A** -> { { domain: tvOS, introduced: 3 }, { domain: watchOS, introduced: 2.0 }, { domain: iOS, introduced: 1.0 } }

-----

Now it behaves like the following:

#### **Input:** 
tvOS-swift.symbols.json:
**A** -> { domain: tvOS }
watchOS-swift.symbols.json:
**A** -> { domain: watchOS, introduced: 8 }

Info.plist:
| tvOS | 3.0 |
| watchOS | 2.0 |
| iOS | 1.0 |

#### **Symbols after symbol graph loading:**
**A** -> { { domain: tvOS, introduced: 3 } }
**A** -> { { domain: watchOS, introduced: 8.0 } }

#### **Resulting symbol availability in the docs:**
**A** -> { { domain: tvOS, introduced: 3 }, { domain: watchOS, introduced: 8.0 } }

## Dependencies

N/A

## Testing

Steps:
1. Preview the attached documentation catalog with the provided SGFs
2. Assert that the symbol A: 
   - Is not available in VisionOS
   - Is available in watchOS from version 12 (availability defined in SGF)
   - Is available in tvOS from version 1.0 (availability defined in info.plist)

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- [X] Added tests
- [ ] Ran the `./bin/test` script and it succeeded
- [ ] Updated documentation if necessary

2024-02-02 17:04 UTC, d-ronnqvist commented
> Now it behaves like the following:
> 
> ...
> 
> Info.plist:
> | tvOS | 3.0 |
> | watchOS | 2.0 |
> | iOS | 1.0 |
> 
> ...
> 
> Resulting symbol availability in the docs:
> 
> A -> { { domain: tvOS, introduced: 3 }, { domain: watchOS, introduced: 8.0 } }

I'm not sure that this is the right behavior but I could be convinced that it is. 

I would have thought that this example would display iOS availability because a default value was specified in the Info.plist and there wasn't an iOS symbol graph file to provide more accurate, per-symbol availability for iOS. 

In my mind, the lack of a symbol graph file for a given platform doesn't mean that the project is unavailable for that platform, just that there's no per-symbol availability information for that platform.

2024-02-02 18:40 UTC, sofiaromorales commented
> I would have thought that this example would display iOS availability because a default value was specified in the Info.plist and there wasn't an iOS symbol graph file to provide more accurate, per-symbol availability for iOS.

In the example described, I chose not to define any iOS SGF. This decision wasn't necessarily due to its nonexistence but rather because it lacks the symbol 'A.' 

The way I see it is that the SGF is the source of truth for per-symbol availability information. If a symbol is not defined in the iOS SGF then it's because the non-existence on that platform. Default availability is useful when the symbol is available for a given platform but doesn't specify the introduced version; in such case it uses the default one, like I showed in the example for tvOS.

The main reason why I think this is how it should behave is because the Swift compiler can't tell the unavailability of a symbol; instead, the symbol simply does not exist within the scope of that platform (in contrast to the clang compiler, which provides information on unavailability), so, identifying the unavailability of a symbol on a platform involves comparing the domains where the symbol is defined against all other defined platforms. The difference operation between these two sets indicates the unavailable platforms.

> In my mind, the lack of a symbol graph file for a given platform doesn't mean that the project is unavailable for that platform, just that there's no per-symbol availability information for that platform.

I don't share this idea because SGFs are essentially the JSON representation of the API. Therefore, the idea of being able to overwrite it through an info.plist file seems inappropriate to me. 

> I'm not sure that this is the right behavior but I could be convinced that it is.

I'm happy to further discuss this with you.

2024-02-05 10:57 UTC, sofiaromorales commented
Similar to this https://github.com/apple/swift-docc/pull/807#pullrequestreview-1853490692 we can consider a `unconditionallyAvailable` property to cover the case you are mentioning.

2024-02-05 11:40 UTC, d-ronnqvist commented
> In the example described, I chose not to define any iOS SGF. This decision wasn't necessarily due to its nonexistence but rather because it lacks the symbol 'A.'

That doesn't match the behavior of either Swift of Clang. If you extract symbols for a module without any public symbols you still get a symbol graph file with an empty list of symbols.

> The way I see it is that the SGF is the source of truth for per-symbol availability information. If a symbol is not defined in the iOS SGF then it's because the non-existence on that platform. Default availability is useful when the symbol is available for a given platform but doesn't specify the introduced version; in such case it uses the default one, like I showed in the example for tvOS.

I agree with this. However, the lack of a symbol graph _file_ for a platform doesn't mean that the module is unconditionally unavailable for that platform. 

----

I agree that _if_ there was an iOS symbol graph file and "A" wasn't in it, then A shouldn't display the default iOS availability from the Info.plist because the iOS symbol graph file provides more accurate, per-symbol information. 

However, the way this PR is currently implemented; "A" doesn't get the default iOS availability (from the Info.plist) unless there's also an iOS symbol graph file and I feel like _that_ is incorrect behavior.

2024-02-15 23:03 UTC, binamaniar commented on Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift
> +                        guard newAvailabilityItems.contains(where: {
How about traversing this through defaultAvailabiliy platform to check if it is present in newAvailabilityItems?

2024-02-15 23:20 UTC, binamaniar requested changes
@mayaepps @patshaughnessy and I went over this PR. 

Loved going through your PR, and the explanation provided, thank you, the examples were great. 

Give the new focus is on symbol graph availabilities and not default availabilities, it might make sense to refactor the code, specifically the loop over defaultAvailabilities seemed confusing to us, it might be simpler to loop over newAvailabilityItems.

2024-02-15 23:20 UTC, binamaniar commented on Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift
>                      for defaultAvailability in defaultAvailabilities {
would this code be easier to read if we loop over newAvailabilityItems instead of defaultAvailabilities? and refactor what the loop does?

2024-02-15 23:20 UTC, binamaniar commented on Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift
>                          let hasAvailabilityForThisPlatform = newAvailabilityItems.contains {
Will this always be true since you added a guard above?

2024-02-15 23:20 UTC, binamaniar commented on Sources/SwiftDocC/Infrastructure/Symbol Graph/SymbolGraphLoader.swift
> +                            return PlatformName(operatingSystemName: $0.domain!.rawValue) == defaultAvailability.platformName
what is the difference between platformName and platformName.rawValue? and why we are comparing these two different things in two places.

2024-02-15 23:25 UTC, mayaepps commented
> However, the way this PR is currently implemented; "A" doesn't get the default iOS availability (from the Info.plist) unless there's also an iOS symbol graph file and I feel like _that_ is incorrect behavior.

@d-ronnqvist Can you give an example of a scenario in which there would not be a iOS symbol graph file, but we would want to give symbols default iOS availability?

2024-02-16 10:00 UTC, d-ronnqvist commented
> > However, the way this PR is currently implemented; "A" doesn't get the default iOS availability (from the Info.plist) unless there's also an iOS symbol graph file and I feel like _that_ is incorrect behavior.
> 
> @d-ronnqvist Can you give an example of a scenario in which there would not be a iOS symbol graph file, but we would want to give symbols default iOS availability?

The simplest example would be when building documentation for any multi platform target in Swift PM or in Xcode. That build is only for one platform at a time, meaning that if you built for macOS you won't have an iOS symbol graph file in that particular build. 

Sofia has more details on various scenarios and what availability information is available to DocC.

2024-03-20 15:57 UTC, closed without merging