Document the supported arguments, flags, and options for DocC's CLI
apple/swift-docc pull request #837
Opened 2024-02-20 13:52 UTC by d-ronnqvist

Bug/issue #, if applicable: rdar://119262681

## Summary

This publishes a refinement of the command line help text for the `docc` executable's commands in the hosted documentation. For example: 

<img width="1571" alt="Screenshot 2024-02-20 at 14 48 16" src="https://github.com/apple/swift-docc/assets/1228143/0d7974b9-5c4d-4bf9-bc22-8439d6b129cc">

<img width="1571" alt="Screenshot 2024-02-20 at 14 45 35" src="https://github.com/apple/swift-docc/assets/1228143/b9ca5fb9-badb-468a-ad19-d23e891bf021">

## Dependencies

None 

## Testing

Run `docc preview Sources/docc/DocCDocumentation.docc` and inspect the documented commands.

## Checklist

Make sure you check off the following items. If they cannot be completed, provide a reason.

- ~[ ] Added tests~
- [x] Ran the `./bin/test` script and it succeeded
- [x] Updated documentation if necessary

2024-02-21 18:21 UTC, patshaughnessy requested changes
I'd just fix the one typo, but I left a few other optional suggestions also.

2024-02-21 18:21 UTC, patshaughnessy commented on Sources/docc/DocCDocumentation.docc/Commands/index.md
> +If you pass the `--emit-lmdb-index` flag to the ``convert`` command, `docc` will create an LMDB index during the build so that you don't need to process the archive after it's been built.
Maybe add another sentence here explaining that this is equivalent to using `docc convert --emit-lmdb-index`, and that you would use this when the archive was already created.

2024-02-21 18:21 UTC, patshaughnessy commented on Sources/docc/DocCDocumentation.docc/Commands/init.md
> +Create a documentation catalog from a template.
I'd rewrite this abstract to focus on the result, and not on the template:

```suggestion
Create a new documentation catalog you can use as a starting point for your project.
```

2024-02-21 18:21 UTC, patshaughnessy commented on Sources/generate-symbol-graph/main.swift
> +        .flatMap { [$0, .init(kind: .text, spelling: " ", preciseIdentifier: nil)] }
Could you use `joined(separator:)` here instead? Seems like the perfect use case for it.

2024-02-21 23:38 UTC, mayaepps reviewed
Thanks for writing these docs! I think it will be very helpful, I just had a few optional questions.

2024-02-21 23:38 UTC, mayaepps commented on Sources/docc/DocCDocumentation.docc/Commands/convert.md
> +  The root path on disk of the repository's checkout.
How does using this option affect what `convert` does?

I also have the same question for the next two options too 😄

2024-02-21 23:38 UTC, mayaepps commented on Sources/docc/DocCDocumentation.docc/Commands/convert.md
> +  Path to the documentation catalog ('.docc') directory.
What is used if no `catalog-path` is provided?

2024-02-23 17:09 UTC, d-ronnqvist commented on Sources/docc/DocCDocumentation.docc/commands.md
> +### Get started
It's the same order that the commands are presented if you run `docc --help`

2026-06-03 08:38 UTC, d-ronnqvist commented
I'll close this PR to reduce noise in the list of open PRs.

I still feel that it would be beneficial to lift the help text into documentation pages but we may need to either improve the help text before that or agree that the initial documentation won't be any better than the current help text.

2026-06-03 08:38 UTC, closed without merging