[NFC] .github: Link out to Swift.org for release branch PR form
apple/swift-docc pull request #940
Opened 2024-06-04 17:26 UTC by AnthonyLatsis

## Summary

In an effort to centralize the release branch PR form and nomination process, provide a link to the section containing the form on Swift.org in the PR templates.

## Checklist

This change is NFC.

2024-06-18 13:34 UTC, Kyle-Ye requested changes

2024-06-18 13:34 UTC, Kyle-Ye commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
Personally, I'm -1 on this.

The originally markdown file gives us a nice template to start with.

But I agree the idea of centering the template across Swift project.

2024-06-18 13:40 UTC, AnthonyLatsis commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
I know, it sucks, but we believe one more layer of indirection is an acceptable compromise. You can follow the link to the form directly from the default PR template too, no need to manually switch to this one.

2024-06-18 13:47 UTC, Kyle-Ye commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
Sorry I ignored the fact that "This move was agreed upon by the Contributor Experience Workgroup."

By the way, do we have some sort of Contributor Experience Workgroup Meeting notes like other workgroup? (eg. SDWG / SSWG / SWWG have it published on the forum)

I'm not doubt the authenticity, just want to know more relevant context here.

2024-06-18 13:52 UTC, d-ronnqvist requested changes

2024-06-18 13:52 UTC, d-ronnqvist commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
Yes. It'd be great to have a link to the meeting notes to understand more about what problem this is solving and who participated in that discussion.

2024-06-18 13:54 UTC, AnthonyLatsis commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
> By the way, do we have some sort of Contributor Experience Workgroup Meeting notes like other workgroup?

No, we don’t have a public meeting record. I will put this on the agenda for next meeting and let you know how it went.

cc @xedin

2024-06-18 13:54 UTC, Kyle-Ye requested changes
Instead of using https://github.com/swiftlang/swift-org-website/pull/688

I'd like to add a new .github repo on swiftlang and add PULL_REQUEST_TEMPLATE/CHERRY_PICK.md file here.

See more information here.

- https://github.blog/changelog/2019-02-21-organization-wide-community-health-files/

Saying that I do not have the permission to create the repo.

Do we need to re-disccuss this again on the next Contributor Experience Workgroup meeting?

2024-06-18 14:24 UTC, AnthonyLatsis commented
> I'd like to suggest we add a new .github repo on swiftlang and add PULL_REQUEST_TEMPLATE/CHERRY_PICK.md file on this repo.

Yep, that was the original idea — suboptimal for `apple`, but much better for `swiftlang`. We’re going to discuss this next meeting (I was the one to originally bring up this topic and nobody seemed to be anticipating `swiftlang` at the time).

@parispittman Do we have a rough estimate on the time frame of repository transfers to `swiftlang`?

2024-06-18 14:37 UTC, Kyle-Ye commented
> > I'd like to suggest we add a new .github repo on swiftlang and add PULL_REQUEST_TEMPLATE/CHERRY_PICK.md file on this repo.
> 
> Yep, that was the original idea — suboptimal for `apple`, but much better for `swiftlang`. We’re going to discuss this next meeting (I was the one to originally bring up this topic and nobody seemed to be anticipating `swiftlang` at the time).
> 
> @parispittman Do we have a rough estimate on the time frame of repository transfers to `swiftlang`?

I saw the transition has already began.

I suggest we just use "the original idea".

For those repo still hosted on apple currently (eg. swift-docc), we can continue use the old pattern.

When the migration is done for them, we can then just safely delete the duplicated .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md file on those repo.

2024-06-18 14:56 UTC, AnthonyLatsis commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
> It'd be great to have a link to the meeting notes to understand more about what problem

To expand on the PR description, the problem is that different repositories have their own versions of the release branch PR form, I suppose mainly because no one updates them, and then there is yet another version that gets published on the forums with every [release process announcement topic](https://forums.swift.org/t/swift-6-0-release-process/70220#pull-requests-for-release-branch-8). These topics also suggest that the form must be central, and we are trying to clean things up and establish a open source place for it to live in, such that repositories can refer to it while people can propose changes to it though pull requests.

2024-06-19 16:44 UTC, AnthonyLatsis commented on .github/PULL_REQUEST_TEMPLATE/CHERRY_PICK.md
> Yes. It'd be great to have a link to the meeting notes to understand more about what problem this is solving and who participated in that discussion.

2024-06-21 02:38 UTC, AnthonyLatsis commented
Turns out, folks have already added a `.github` repository to `swiftlang`, so I went ahead and [added](https://github.com/swiftlang/.github/pull/2) the org-wide pull request template. It works as a query parameter just fine. The template is called `release.md` — I think this neutral and simple if straightforward name will be easiest for us all to remember and type.  I will update this pull request accordingly as soon as the repo moves to `swiftlang`.  

Thanks for weighing in!

2024-07-12 03:39 UTC, Kyle-Ye requested changes
Another thing I'd like to confirm is that after your PR we should continue to be able to create cherry-pick/release template PR via GitHub's official command line tool - gh.

<img width="1092" alt="image" src="https://github.com/user-attachments/assets/363ff965-fdff-4149-bb98-d5ea398ade0e">

But it seems we will lose the template discovery after your PR. (Delete CHERRY_PICK.md but not adding swiftlang/.github's release.md)

I do not know if this a bug on gh or a misconfiguration on swiftlang/.github repo.

See discussion here for more information https://github.com/swiftlang/swift-docc/pull/300#issuecomment-1155166707

2024-07-17 00:33 UTC, AnthonyLatsis commented
Confirmed using my swift fork:

<img width="906" alt="Screenshot 2024-07-17 at 02 53 46" src="https://github.com/user-attachments/assets/c51dd930-2b7d-416e-85b6-13551bd7efd1">

> But it seems we will lose the template discovery after your PR.

Because this repository will no longer have its own template, you mean? I believe that is fine:
* We still have a leading comment in the default template.
* Folks that submit changes to release branches on a regular basis have the experience to catch on.
* First-timers are in the majority of cases asked by code owners to cherry-pick something and receive appropriate guidance. One can also learn about the template and how to tap into it from the website: https://www.swift.org/contributing/#release-branch-pull-requests.

2024-07-17 01:13 UTC, AnthonyLatsis commented
> Confirmed with the swift repository, which no longer has a release template.

It seems I was wrong. I tried again with the Apple `main` branch vs. my fork as the base and now it only shows the default template. `release.md` is only shown when the repository has no PR templates at all, like swift-syntax. 😕

2025-12-03 12:32 UTC, Kyle-Ye approved these changes

2026-06-04 15:51 UTC, snprajwal commented
https://github.com/cli/cli/pull/9863 fixed the issue with GitHub CLI, is there anything blocking us now @AnthonyLatsis? If this is merged, are we able to use this new template the same way as the current `CHERRY_PICK.md` template?

2026-06-10 12:50 UTC, snprajwal approved these changes
@AnthonyLatsis confirmed that this now works as expected with Github CLI too. LGTM

2026-06-10 12:51 UTC, d-ronnqvist approved these changes

2026-06-10 12:51 UTC, snprajwal commented
@swift-ci please test

2026-06-10 12:57 UTC, AnthonyLatsis commented
<img width="694" height="223" alt="Screenshot 2026-06-10 at 13 24 06" src="https://github.com/user-attachments/assets/c0900760-1242-4de4-a5c6-045b47a2b78e" />

2026-06-10 12:59 UTC, merged